version: "3.7"

services:

  java:
    build: java
    volumes:
      - ./:/app
    working_dir: /app
    stdin_open: true
    tty: true
    command: /bin/bash

  python:
    build: python
    volumes:
      - ./:/app
    working_dir: /app
    stdin_open: true
    tty: true
    command: /bin/bash
